#include <stdio.h>  
#include <string.h>  
int main(){  
		int i,j;  
		while(scanf("%d %d",&i,&j)!=EOF){  
				if(i==1){  
						if(j>=21)  
								printf("Aquarius\n");  
						else  
								printf("Capricorn\n");  
				}  
				if(i==2){  
						if(j>=19)  
								printf("Pisces\n");  
						else  
								printf("Aquarius\n");  
				}  
				if(i==3){  
						if(j>=21)  
								printf("Aries\n");  
						else  
								printf("Pisces\n");  
				}  
				if(i==4){  
						if(j>=21)  
								printf("Taurus\n");  
						else  
								printf("Aries\n");  
				}  
				if(i==5){  
						if(j>=22)  
								printf("Gemini\n");  
						else  
								printf("Taurus\n");  
				}  
				if(i==6){  
						if(j>=22)  
								printf("Cancer\n");  
						else  
								printf("Gemini\n");  
				}  
				if(i==7){  
						if(j>=23)  
								printf("Leo\n");  
						else  
								printf("Cancer\n");  
				}  
				if(i==8){  
						if(j>=24)  
								printf("Virgo\n");  
						else  
								printf("Leo\n");  
				}  
				if(i==9){  
						if(j>=24)  
								printf("Libra\n");  
						else  
								printf("Virgo\n");  
				}  
				if(i==10){  
						if(j>=24)  
								printf("Scorpio\n");  
						else  
								printf("Libra\n");  
				}  
				if(i==11){  
						if(j>=23)  
								printf("Sagittarius\n");  
						else  
								printf("Scorpio\n");  
				}  
				if(i==12){  
						if(j>=22)  
								printf("Capricorn\n");  
						else  
								printf("Sagittarius\n");  
				}  
		}  
		return 0;  
}  
